services:
  web_api:
    container_name: tictactoe_api
    build: .
    image: ttfmodulbank
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: passsword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
volumes:
  postgres_data: